### ISSUE TITLE
Doesn't prefix `transform` and `translateX` correctly

### ISSUE THREAD

**Issue by winston0410** [robinweser/inline-style-prefixer#202]
I found out that prefixer doesn't prefix `transform` and `translateX` correctly.

```javascript
import { prefix } from 'inline-style-prefixer'
const mockDecl = {
  transform: 'translateX(2em)'
}

console.log('prefixer result', prefix(mockDecl))
```

This code will log this:
```javascript
{ transform: 'translateX(2em)' }
```

Instead of:

```javascript
{
webkitTransform: 'translateX(2em)',
    msTransform: 'translateX(2em)',
        transform: 'translateX(2em)'
}
```

**Comment by robinweser** [comment]
This is due to the browser support of `transform`. The default browser settings, which you can find in the README, don't require `transform` to be prefixed at all. After all, it's pretty much supported in every modern browser.

If you still need it to be prefixed, I'd recommend to create your custom prefixer (see the docs on how to do that) which a custom browser version range.
